---
sudo: false
matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOXENV=cov
      after_success: codecov
    - python: "3.6"
      env: TOXENV=lint
    - python: "3.6"
      env: TOXENV=py36

language: python
install: pip install -U codecov tox
script: tox --develop
cache:
  directories:
  - $HOME/.cache/pip
