version: 2.1

executors:
  python:
    parameters:
      tag:
        type: string
        default: latest
    docker:
      - image: circleci/python:<< parameters.tag >>
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/repo

commands:
  install-requirments:
    description: Set up venv and install requirements python packages with cache support
    parameters:
      pyver:
        type: string
        default: "3.7"
    steps:
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python<< parameters.pyver >>/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install dependencies
          command: |
            sudo pip install pipenv
            pipenv install --dev --bare
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python<< parameters.pyver >>/site-packages"

jobs:
  lint:
    executor:
      name: python
      tag: "3.7"
    steps:
      - checkout
      - install-requirments:
          pyver: "3.7"
      - run:
          name: run linter
          command: pipenv run make lint

workflows:
  version: 2
  build:
    jobs:
      - lint
