version: 2.1




common: &common
  working_directory: ~/repo
  steps:
    - checkout
    - restore_cache:
        keys:
          - v2-deps-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
#     - run:
#         name: install dependencies
#         command: |
#           sudo pip install pipenv
#           pipenv --python 3.7
#           pipenv install --dev
#     - save_cache:
#         key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
#         paths:
#           - ".venv"
#           - "/usr/local/bin"
#           - "/usr/local/lib/python3.7/site-packages"
    - run:
        name: run tox
        command: pipenv run tox
    - run:
        name: upload coverage report
        command: |
           if [[ "$UPLOAD_COVERAGE" != 0 ]]; then
               PATH=$HOME/.local/bin:$PATH
               pip install --user codecov
               coverage xml
               ~/.local/bin/codecov --required -X search gcov pycov -f coverage.xml --flags $CIRCLE_JOB
           fi
    - save_cache:
        paths:
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
        key: v2-deps-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

#py36, py37, py38, cov, lint, typing
jobs:
  lint:
    docker:
      - image: circleci/python:3.7.2
        environment:
          - TOXENV=lint
          - UPLOAD_COVERAGE=0

  py37:
    docker:
      - image: circleci/python:3.7.2
        environment:
          TOXENV=py37

  cov:
    docker:
      - image: circleci/python:3.7.2
        environment:
          TOXENV=cov

  typing:
    docker:
      - image: circleci/python:3.7.2
        environment:
          TOXENV=typing

  build:
    docker:
      - image: circleci/python:3.7.2
      - image: circleci/buildpack-deps:stretch

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv --python 3.7
            pipenv install
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"

workflows:
  version: 2
  test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - cov:
          requires:
            - build
      - py37:
          requires:
            - build
      - typing:
          requires:
            - build
