version: 2.1

executors:
  python:
    parameters:
      tag:
        type: string
        default: latest
    docker:
      - image: circleci/python:<< parameters.tag >>
    working_directory: ~/repo

commands:
  install-requirments:
    description: Set up venv and install requirements python packages with cache support
    parameters:
      pyver:
        type: string
        default: "3.7"
    steps:
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python<< parameters.pyver >>/site-packages
      - restore_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install dependencies
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "~/repo"
            - "/.local/share/virtualenv"
            - "/usr/local/bin"
            - "/usr/local/lib/python<< parameters.pyver >>/site-packages"

  checkout_code:
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

jobs:
  build:
    executor:
      name: python
      tag: "3.7"
    steps:
      - checkout_code
      - install-requirments:
          pyver: "3.7"

  lint:
    executor:
      name: python
      tag: "3.7"
    steps:
      - run:
          name: run linter
          command: pipenv run make lint

  test:
    executor:
      name: python
      tag: "3.7"
    steps:
      - run:
          name: run test suite
          command: pipenv run make test

workflows:
  version: 2
  build:
    jobs:
      - build
      - lint:
          requires:
            - build
